DROP TABLE IF EXISTS dt01_gen_auth_url_sign_dt;

CREATE TABLE `dt01_gen_auth_url_sign_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `URL_ID` varchar(36) NOT NULL,
  `REQUEST_ID` varchar(36) NOT NULL,
  `USER_IDENTIFIER` varchar(1000) NOT NULL,
  `URL` varchar(1000) NOT NULL,
  `STATUS` varchar(1) NOT NULL DEFAULT '0' COMMENT '0 : New / File Baru Di Upload\r\n1 : Success Execute Sign\r\n2 : Document Success Sign\r\n3 : File Berhasil Di Download',
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`URL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_document_file_dt;

CREATE TABLE `dt01_gen_document_file_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `NO_FILE` varchar(100) NOT NULL,
  `FILENAME` varchar(1000) DEFAULT NULL,
  `JENIS_DOC` varchar(10) DEFAULT NULL,
  `ASSIGN` varchar(1000) DEFAULT NULL,
  `STATUS_SIGN` varchar(1) NOT NULL DEFAULT '0' COMMENT '0 : File Not Uploaded / File Belum Di Upload\r\n1 : Files Have Been Uploaded / File Sudah Di Upload\r\n2 : Request Sign Success / Sedang Process Pengajuan Tanda Tangan\r\n3 : Request Sign Gagal / Sedang Process Pengajuan Tanda Tangan\r\n4 : Sign Success / Tanda Tangan Berhasil\r\n5 : Sign Gagal/ Tanda Tangan Berhasil',
  `LINK` varchar(1000) DEFAULT NULL,
  `PASIEN_IDX` varchar(1000) DEFAULT NULL,
  `TRANSAKSI_IDX` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `REQUEST_ID` varchar(36) DEFAULT NULL,
  `NOTE` text NOT NULL,
  `SOURCE_FILE` varchar(255) DEFAULT NULL,
  `STATUS_FILE` varchar(1) DEFAULT '0',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `USER_IDENTIFIER` varchar(1000) DEFAULT NULL,
  `URL` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_document_ms;

CREATE TABLE `dt01_gen_document_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `JENIS_DOC` varchar(10) NOT NULL,
  `DOCUMENT_NAME` varchar(100) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`JENIS_DOC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_enviroment_ms;

CREATE TABLE `dt01_gen_enviroment_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `ENV_ID` varchar(36) NOT NULL,
  `ENVIRONMENT_NAME` varchar(1000) NOT NULL,
  `DEV` varchar(1000) NOT NULL,
  `PROD` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `URUT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ENV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_level_fungsional_ms;

CREATE TABLE `dt01_gen_level_fungsional_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `LEVEL_ID` varchar(36) NOT NULL,
  `LEVEL` varchar(100) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) NOT NULL,
  `LAST_UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`LEVEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_level_user_ms;

CREATE TABLE `dt01_gen_level_user_ms` (
  `LEVEL_ID` varchar(36) NOT NULL,
  `LEVEL` varchar(500) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`LEVEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_modules_ms;

CREATE TABLE `dt01_gen_modules_ms` (
  `MODULES_ID` varchar(36) NOT NULL,
  `MODULES_NAME` varchar(100) NOT NULL,
  `VERSION` varchar(100) NOT NULL,
  `MODULES_HEADER_ID` varchar(36) NOT NULL,
  `PACKAGE` varchar(100) NOT NULL,
  `DEF_CONTROLLER` varchar(100) NOT NULL,
  `PARENT` varchar(1) NOT NULL DEFAULT 'N',
  `ICON` varchar(500) NOT NULL,
  `STATUS` varchar(1) NOT NULL DEFAULT '0',
  `URUT` int(11) NOT NULL DEFAULT 0,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`MODULES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_organization_ms;

CREATE TABLE `dt01_gen_organization_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `ORG_NAME` varchar(4000) NOT NULL,
  `WEBSITE` varchar(1000) NOT NULL,
  `TRIAL` varchar(1) NOT NULL DEFAULT 'Y',
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `CODE` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`ORG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_referensi_dt;

CREATE TABLE `dt01_gen_referensi_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `REF_ID` varchar(36) NOT NULL,
  `REFERENSI` varchar(100) NOT NULL,
  `NOTE` varchar(4000) NOT NULL,
  `LINK` varchar(1000) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`REF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_role_access;

CREATE TABLE `dt01_gen_role_access` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `TRANS_ID` varchar(36) NOT NULL,
  `USER_ID` varchar(36) DEFAULT NULL,
  `ROLE_ID` varchar(36) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) DEFAULT NULL,
  `LAST_UPDATE_DATE` date DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_role_dt;

CREATE TABLE `dt01_gen_role_dt` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `TRANS_ID` varchar(36) NOT NULL,
  `ROLE_ID` varchar(36) DEFAULT NULL,
  `MODULES_ID` varchar(36) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) DEFAULT NULL,
  `LAST_UPDATE_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_role_ms;

CREATE TABLE `dt01_gen_role_ms` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `ROLE_ID` varchar(36) NOT NULL,
  `ROLE` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `LAST_UPDATED_BY` varchar(36) DEFAULT NULL,
  `LAST_UPDATED_DATE` datetime DEFAULT current_timestamp(),
  `TRANS_ID` varchar(50) DEFAULT NULL,
  `USER_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_gen_user_data;

CREATE TABLE `dt01_gen_user_data` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `USERNAME` varchar(4000) NOT NULL,
  `USER_IDENTIFIER` varchar(1000) NOT NULL,
  `PASSWORD` varchar(4000) NOT NULL DEFAULT '3832333435363731',
  `NIK` varchar(100) NOT NULL COMMENT 'Nomor Induk Kepegawaian',
  `NIP` varchar(100) DEFAULT NULL COMMENT 'NIP PNS Jika DiPerlukan',
  `NAME` varchar(1000) NOT NULL,
  `SEX_ID` varchar(1) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `IDENTITY_NO` varchar(16) DEFAULT NULL COMMENT 'No KTP',
  `NPWP_NO` varchar(100) DEFAULT NULL,
  `ADDRESS` varchar(4000) DEFAULT NULL,
  `KATEGORI_ID` varchar(36) DEFAULT NULL,
  `SUSPENDED` varchar(1) NOT NULL DEFAULT 'N',
  `REGISTER_ID` varchar(36) NOT NULL,
  `TILAKA_ID` varchar(100) NOT NULL,
  `REVOKE_ID` varchar(39) NOT NULL,
  `ISSUE_ID` varchar(42) NOT NULL,
  `CERTIFICATE` varchar(1) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `PLACE_BIRTH` varchar(100) DEFAULT NULL,
  `IMAGE_PROFILE` varchar(1) NOT NULL DEFAULT 'N',
  `IMAGE_IDENTITY` varchar(1) NOT NULL DEFAULT 'N',
  `LEVEL_USER` varchar(36) NOT NULL DEFAULT 'a3b109d6-b792-4883-b176-31bc762de98d',
  `NAME_IDENTITY` varchar(1000) DEFAULT NULL,
  `KLINIS_ID` varchar(36) DEFAULT NULL,
  `DUTY_DAYS` int(11) DEFAULT 0,
  `DUTY_HOURS` int(11) DEFAULT 0,
  `HOURS_MONTH` int(11) DEFAULT 0,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_activity_dt;

CREATE TABLE `dt01_hrd_activity_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `TRANS_ID` varchar(36) NOT NULL,
  `ACTIVITY_ID` varchar(36) NOT NULL,
  `START_DATE` date DEFAULT NULL,
  `START_TIME_IN` varchar(5) DEFAULT NULL,
  `START_TIME_OUT` varchar(5) DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `END_TIME_IN` varchar(5) NOT NULL,
  `END_TIME_OUT` varchar(5) NOT NULL,
  `QTY` int(11) NOT NULL DEFAULT 0,
  `DURASI` int(11) NOT NULL DEFAULT 0,
  `TOTAL` int(11) NOT NULL DEFAULT 0,
  `ACTIVITY` text NOT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `ATASAN_ID` varchar(36) NOT NULL,
  `VALIDASI_BY` varchar(36) NOT NULL,
  `VALIDASI_DATE` datetime DEFAULT NULL,
  `STATUS` varchar(1) NOT NULL DEFAULT '0' COMMENT '0 : Baru\r\n1 : Disetujui\r\n2 : Revisi\r\n9 : Di Tolak',
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_activity_ms;

CREATE TABLE `dt01_hrd_activity_ms` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `ACTIVITY_ID` varchar(36) NOT NULL,
  `ACTIVITY` varchar(256) DEFAULT NULL,
  `DURASI` int(11) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) DEFAULT NULL,
  `LAST_UPDATE_DATE` datetime DEFAULT current_timestamp(),
  `PK` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`ACTIVITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_address_dt;

CREATE TABLE `dt01_hrd_address_dt` (
  `ADDRESS_ID` varchar(100) NOT NULL,
  `USER_ID` varchar(100) DEFAULT NULL,
  `ADDRESS_LABEL` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT sysdate(),
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `PRIMARY` varchar(2) DEFAULT NULL,
  `ACTIVE` varchar(2) DEFAULT '1',
  PRIMARY KEY (`ADDRESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS dt01_hrd_assessment_dt;

CREATE TABLE `dt01_hrd_assessment_dt` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `TRANSAKSI_ID` varchar(36) NOT NULL,
  `USER_ID` varchar(36) DEFAULT NULL,
  `PERIODE` varchar(7) DEFAULT NULL,
  `ASSESSMENT_ID` varchar(100) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `NILAI` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRANSAKSI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_assessment_ms;

CREATE TABLE `dt01_hrd_assessment_ms` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `ASSESSMENT_ID` varchar(36) NOT NULL,
  `ASSESSMENT` varchar(1000) DEFAULT NULL,
  `JENIS` varchar(1) DEFAULT NULL,
  `HEADER_ID` varchar(36) DEFAULT NULL,
  `KATEGORI_ID` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ASSESSMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_contact_dt;

CREATE TABLE `dt01_hrd_contact_dt` (
  `CONTACT_ID` varchar(100) NOT NULL,
  `USER_ID` varchar(100) DEFAULT NULL,
  `CONTACT_NAME` varchar(255) DEFAULT NULL,
  `CONTACT_PHONE` varchar(255) DEFAULT NULL,
  `CONTACT_ADDRESS` varchar(255) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_DATE` datetime DEFAULT sysdate(),
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `RELATIONSHIP_ID` varchar(100) DEFAULT NULL,
  `CONTACT_PRIMARY` varchar(2) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS dt01_hrd_kategori_tenaga_ms;

CREATE TABLE `dt01_hrd_kategori_tenaga_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `KATEGORI_ID` varchar(36) NOT NULL,
  `KATEGORI` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`KATEGORI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS dt01_hrd_klinis_ms;

CREATE TABLE `dt01_hrd_klinis_ms` (
  `KLINIS_ID` varchar(36) NOT NULL,
  `NAME` varchar(1000) NOT NULL,
  `AREA` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `NOMOR` int(11) DEFAULT 0,
  PRIMARY KEY (`KLINIS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_mapping_activity;

CREATE TABLE `dt01_hrd_mapping_activity` (
  `ORG_ID` varchar(36) NOT NULL,
  `TRANSAKSI_ID` varchar(36) NOT NULL,
  `POSITION_ID` varchar(36) NOT NULL,
  `ACTIVITY_ID` varchar(36) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) DEFAULT NULL,
  `LAST_UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`TRANSAKSI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_mapping_klinis;

CREATE TABLE `dt01_hrd_mapping_klinis` (
  `TRANSAKSI_ID` varchar(36) NOT NULL,
  `KLINIS_ID` varchar(36) NOT NULL,
  `SUB_KLINIS_ID` varchar(36) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANSAKSI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_meeting_dt;

CREATE TABLE `dt01_hrd_meeting_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `MEETING_ID` varchar(36) NOT NULL,
  `JENIS_ID` varchar(36) NOT NULL,
  `DATE` date NOT NULL,
  `START_TIME` varchar(5) NOT NULL,
  `END_TIME` varchar(5) NOT NULL,
  `MEETING` varchar(1000) NOT NULL,
  `DESCRIPTION` varchar(1000) NOT NULL,
  `URL` varchar(1000) DEFAULT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`MEETING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_meeting_ms;

CREATE TABLE `dt01_hrd_meeting_ms` (
  `ORG_ID` varchar(36) NOT NULL,
  `MEETING_ID` varchar(36) NOT NULL,
  `MEETING` varchar(1000) NOT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`MEETING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_position_dt;

CREATE TABLE `dt01_hrd_position_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `TRANS_ID` varchar(36) NOT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `POSITION_ID` varchar(36) NOT NULL,
  `ATASAN_ID` varchar(36) NOT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `POSITION_PRIMARY` varchar(1) NOT NULL DEFAULT 'N',
  `STATUS` varchar(1) NOT NULL DEFAULT '1',
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_position_ms;

CREATE TABLE `dt01_hrd_position_ms` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `POSITION_ID` varchar(36) NOT NULL,
  `POSITION` varchar(500) DEFAULT NULL,
  `RVU` int(11) DEFAULT NULL,
  `LEVEL_FUNGSIONAL` varchar(36) NOT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(36) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  `LAST_UPDATE_BY` varchar(36) NOT NULL,
  `LAST_UPDATE_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `KATEGORI_ID` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`POSITION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_hrd_relationship_ms;

CREATE TABLE `dt01_hrd_relationship_ms` (
  `RELATIONSHIP_ID` varchar(100) NOT NULL,
  `RELATIONSHIP_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RELATIONSHIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS dt01_hrd_todo_dt;

CREATE TABLE `dt01_hrd_todo_dt` (
  `ORG_ID` varchar(36) NOT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `TODO_ID` varchar(36) NOT NULL,
  `TODO` varchar(4000) NOT NULL,
  `PRIORITY` varchar(1) NOT NULL DEFAULT '1',
  `STATUS` varchar(1) NOT NULL DEFAULT '0',
  `DUE_DATE` date DEFAULT NULL,
  `ACTIVE` varchar(1) NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(36) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`TODO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_receivedata_data_leka;

CREATE TABLE `dt01_receivedata_data_leka` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `TRANSAKSI_ID` varchar(36) NOT NULL,
  `ENCOUNTER_ID` varchar(36) DEFAULT NULL,
  `DEVICE_ID` text DEFAULT NULL,
  `EXAM_ID` text DEFAULT NULL,
  `ID_NUMBER` text DEFAULT NULL,
  `NAME` text DEFAULT NULL,
  `SEX` text DEFAULT NULL,
  `BOD` text DEFAULT NULL,
  `AGE` text DEFAULT NULL,
  `NATION` text DEFAULT NULL,
  `ADDRESS` text DEFAULT NULL,
  `PHOTO` text DEFAULT NULL,
  `QRCODE` text DEFAULT NULL,
  `HEIGHT_VALUE` text DEFAULT NULL,
  `HEIGHT_NORMAL` text DEFAULT NULL,
  `HEIGHT_NOTE` text DEFAULT NULL,
  `WEIGHT_VALUE` text DEFAULT NULL,
  `WEIGHT_NORMAL` text DEFAULT NULL,
  `WEIGHT_NOTE` text DEFAULT NULL,
  `BMI_VALUE` text DEFAULT NULL,
  `BMI_NORMAL` text DEFAULT NULL,
  `BMI_NOTE` text DEFAULT NULL,
  `FAT_DBZ_VALUE` text DEFAULT NULL,
  `FAT_DBZ_NORMAL` text DEFAULT NULL,
  `FAT_DBZ_NOTE` text DEFAULT NULL,
  `FAT_DBZLV_VALUE` text DEFAULT NULL,
  `FAT_DBZLV_NORMAL` text DEFAULT NULL,
  `FAT_DBZLV_NOTE` text DEFAULT NULL,
  `FAT_GL_VALUE` text DEFAULT NULL,
  `FAT_GL_NORMAL` text DEFAULT NULL,
  `FAT_GL_NOTE` text DEFAULT NULL,
  `FAT_GY_VALUE` text DEFAULT NULL,
  `FAT_GY_NORMAL` text DEFAULT NULL,
  `FAT_GY_NOTE` text DEFAULT NULL,
  `FAT_JCDX_VALUE` text DEFAULT NULL,
  `FAT_JCDX_NORMAL` text DEFAULT NULL,
  `FAT_JCDX_NOTE` text DEFAULT NULL,
  `FAT_JRL_VALUE` text DEFAULT NULL,
  `FAT_JRL_NORMAL` text DEFAULT NULL,
  `FAT_JRL_NOTE` text DEFAULT NULL,
  `FAT_JRLV_VALUE` text DEFAULT NULL,
  `FAT_JRLV_NORMAL` text DEFAULT NULL,
  `FAT_JRLV_NOTE` text DEFAULT NULL,
  `FAT_NZZF_VALUE` text DEFAULT NULL,
  `FAT_NZZF_NORMAL` text DEFAULT NULL,
  `FAT_NZZF_NOTE` text DEFAULT NULL,
  `FAT_QZTZ_VALUE` text DEFAULT NULL,
  `FAT_QZTZ_NORMAL` text DEFAULT NULL,
  `FAT_QZTZ_NOTE` text DEFAULT NULL,
  `FAT_TSFL_VALUE` text DEFAULT NULL,
  `FAT_TSFL_NORMAL` text DEFAULT NULL,
  `FAT_TSFL_NOTE` text DEFAULT NULL,
  `FAT_TSFLV_VALUE` text DEFAULT NULL,
  `FAT_TSFLV_NORMAL` text DEFAULT NULL,
  `FAT_TSFLV_NOTE` text DEFAULT NULL,
  `FAT_XBNYL_VALUE` text DEFAULT NULL,
  `FAT_XBNYL_NORMAL` text DEFAULT NULL,
  `FAT_XBNYL_NOTE` text DEFAULT NULL,
  `FAT_XBNYLV_VALUE` text DEFAULT NULL,
  `FAT_XBNYLV_NORMAL` text DEFAULT NULL,
  `FAT_XBNYLV_NOTE` text DEFAULT NULL,
  `FAT_XBWYL_VALUE` text DEFAULT NULL,
  `FAT_XBWYL_NORMAL` text DEFAULT NULL,
  `FAT_XBWYL_NOTE` text DEFAULT NULL,
  `FAT_XBWYLV_VALUE` text DEFAULT NULL,
  `FAT_XBWYLV_NORMAL` text DEFAULT NULL,
  `FAT_XBWYLV_NOTE` text DEFAULT NULL,
  `FAT_ZFL_VALUE` text DEFAULT NULL,
  `FAT_ZFL_NORMAL` text DEFAULT NULL,
  `FAT_ZFL_NOTE` text DEFAULT NULL,
  `FAT_ZFLV_VALUE` text DEFAULT NULL,
  `FAT_ZFLV_NORMAL` text DEFAULT NULL,
  `FAT_ZFLV_NOTE` text DEFAULT NULL,
  `BLOOD_HIGH_VALUE` text DEFAULT NULL,
  `BLOOD_HIGH_NORMAL` text DEFAULT NULL,
  `BLOOD_HIGH_NOTE` text DEFAULT NULL,
  `BLOOD_LOW_VALUE` text DEFAULT NULL,
  `BLOOD_LOW_NORMAL` text DEFAULT NULL,
  `BLOOD_LOW_NOTE` text DEFAULT NULL,
  `BLOOD_RATE_VALUE` text DEFAULT NULL,
  `BLOOD_RATE_NORMAL` text DEFAULT NULL,
  `BLOOD_RATE_NOTE` text DEFAULT NULL,
  `SPO2_SP_VALUE` text DEFAULT NULL,
  `SPO2_SP_NORMAL` text DEFAULT NULL,
  `SPO2_SP_NOTE` text DEFAULT NULL,
  `TIWEN_VALUE` text DEFAULT NULL,
  `TIWEN_NORMAL` text DEFAULT NULL,
  `TIWEN_NOTE` text DEFAULT NULL,
  `ECG_DATA_VALUE` text DEFAULT NULL,
  `ECG_RESULT_VALUE` text DEFAULT NULL,
  `ECG_XINLV_VALUE` text DEFAULT NULL,
  `ECG12_DATA_VALUE` text DEFAULT NULL,
  `ECG12_DATA_NORMAL` text DEFAULT NULL,
  `ECG12_DATA_NOTE` text DEFAULT NULL,
  `ECG12_RESULT_VALUE` text DEFAULT NULL,
  `ECG12_RESULT_NORMAL` text DEFAULT NULL,
  `ECG12_RESULT_NOTE` text DEFAULT NULL,
  `ECG12_HEART_RATE_VALUE` text DEFAULT NULL,
  `ECG12_HEART_RATE_NORMAL` text DEFAULT NULL,
  `ECG12_HEART_RATE_NOTE` text DEFAULT NULL,
  `ECG12_P_AXIS_VALUE` text DEFAULT NULL,
  `ECG12_P_AXIS_NORMAL` text DEFAULT NULL,
  `ECG12_P_AXIS_NOTE` text DEFAULT NULL,
  `ECG12_PR_VALUE` text DEFAULT NULL,
  `ECG12_PR_NORMAL` text DEFAULT NULL,
  `ECG12_PR_NOTE` text DEFAULT NULL,
  `ECG12_QRS_VALUE` text DEFAULT NULL,
  `ECG12_QRS_NORMAL` text DEFAULT NULL,
  `ECG12_QRS_NOTE` text DEFAULT NULL,
  `ECG12_QRS_AXIS_VALUE` text DEFAULT NULL,
  `ECG12_QRS_AXIS_NORMAL` text DEFAULT NULL,
  `ECG12_QRS_AXIS_NOTE` text DEFAULT NULL,
  `ECG12_QT_VALUE` text DEFAULT NULL,
  `ECG12_QT_NORMAL` text DEFAULT NULL,
  `ECG12_QT_NOTE` text DEFAULT NULL,
  `ECG12_QTC_VALUE` text DEFAULT NULL,
  `ECG12_QTC_NORMAL` text DEFAULT NULL,
  `ECG12_QTC_NOTE` text DEFAULT NULL,
  `ECG12_RV5_VALUE` text DEFAULT NULL,
  `ECG12_RV5_NORMAL` text DEFAULT NULL,
  `ECG12_RV5_NOTE` text DEFAULT NULL,
  `ECG12_SAMPLE_RATE_VALUE` text DEFAULT NULL,
  `ECG12_SAMPLE_RATE_NORMAL` text DEFAULT NULL,
  `ECG12_SAMPLE_RATE_NOTE` text DEFAULT NULL,
  `ECG12_SAMPLE_TIME_VALUE` text DEFAULT NULL,
  `ECG12_SAMPLE_TIME_NORMAL` text DEFAULT NULL,
  `ECG12_SAMPLE_TIME_NOTE` text DEFAULT NULL,
  `ECG12_SV1_VALUE` text DEFAULT NULL,
  `ECG12_SV1_NORMAL` text DEFAULT NULL,
  `ECG12_SV1_NOTE` text DEFAULT NULL,
  `ECG12_T_AXIS_VALUE` text DEFAULT NULL,
  `ECG12_T_AXIS_NORMAL` text DEFAULT NULL,
  `ECG12_T_AXIS_NOTE` text DEFAULT NULL,
  `XT_TYPE_VALUE` text DEFAULT NULL,
  `XT_TYPE_NORMAL` text DEFAULT NULL,
  `XT_TYPE_NOTE` text DEFAULT NULL,
  `XT_VALUE_VALUE` text DEFAULT NULL,
  `XT_VALUE_NORMAL` text DEFAULT NULL,
  `XT_VALUE_NOTE` text DEFAULT NULL,
  `NS_VALUE` text DEFAULT NULL,
  `NS_NORMAL` text DEFAULT NULL,
  `NS_NOTE` text DEFAULT NULL,
  `DGC_VALUE` text DEFAULT NULL,
  `DGC_NORMAL` text DEFAULT NULL,
  `DGC_NOTE` text DEFAULT NULL,
  `XHDB_HXBYJ_VALUE` text DEFAULT NULL,
  `XHDB_HXBYJ_NORMAL` text DEFAULT NULL,
  `XHDB_HXBYJ_NOTE` text DEFAULT NULL,
  `XHDB_VALUE_VALUE` text DEFAULT NULL,
  `XHDB_VALUE_NORMAL` text DEFAULT NULL,
  `XHDB_VALUE_NOTE` text DEFAULT NULL,
  `XZSX_CHD_VALUE` text DEFAULT NULL,
  `XZSX_CHD_NORMAL` text DEFAULT NULL,
  `XZSX_CHD_NOTE` text DEFAULT NULL,
  `XZSX_CHOL_VALUE` text DEFAULT NULL,
  `XZSX_CHOL_NORMAL` text DEFAULT NULL,
  `XZSX_CHOL_NOTE` text DEFAULT NULL,
  `XZSX_HDL_VALUE` text DEFAULT NULL,
  `XZSX_HDL_NORMAL` text DEFAULT NULL,
  `XZSX_HDL_NOTE` text DEFAULT NULL,
  `XZSX_LDL_VALUE` text DEFAULT NULL,
  `XZSX_LDL_NORMAL` text DEFAULT NULL,
  `XZSX_LDL_NOTE` text DEFAULT NULL,
  `XZSX_TG_VALUE` text DEFAULT NULL,
  `XZSX_TG_NORMAL` text DEFAULT NULL,
  `XZSX_TG_NOTE` text DEFAULT NULL,
  `NYFX_BIL_VALUE` text DEFAULT NULL,
  `NYFX_BIL_NORMAL` text DEFAULT NULL,
  `NYFX_BIL_NOTE` text DEFAULT NULL,
  `NYFX_BLD_VALUE` text DEFAULT NULL,
  `NYFX_BLD_NORMAL` text DEFAULT NULL,
  `NYFX_BLD_NOTE` text DEFAULT NULL,
  `NYFX_CA_VALUE` text DEFAULT NULL,
  `NYFX_CA_NORMAL` text DEFAULT NULL,
  `NYFX_CA_NOTE` text DEFAULT NULL,
  `NYFX_CRE_VALUE` text DEFAULT NULL,
  `NYFX_CRE_NORMAL` text DEFAULT NULL,
  `NYFX_CRE_NOTE` text DEFAULT NULL,
  `NYFX_GLU_VALUE` text DEFAULT NULL,
  `NYFX_GLU_NORMAL` text DEFAULT NULL,
  `NYFX_GLU_NOTE` text DEFAULT NULL,
  `NYFX_KET_VALUE` text DEFAULT NULL,
  `NYFX_KET_NORMAL` text DEFAULT NULL,
  `NYFX_KET_NOTE` text DEFAULT NULL,
  `NYFX_LEU_VALUE` text DEFAULT NULL,
  `NYFX_LEU_NORMAL` text DEFAULT NULL,
  `NYFX_LEU_NOTE` text DEFAULT NULL,
  `NYFX_MA_VALUE` text DEFAULT NULL,
  `NYFX_MA_NORMAL` text DEFAULT NULL,
  `NYFX_MA_NOTE` text DEFAULT NULL,
  `NYFX_NIT_VALUE` text DEFAULT NULL,
  `NYFX_NIT_NORMAL` text DEFAULT NULL,
  `NYFX_NIT_NOTE` text DEFAULT NULL,
  `NYFX_PH_VALUE` text DEFAULT NULL,
  `NYFX_PH_NORMAL` text DEFAULT NULL,
  `NYFX_PH_NOTE` text DEFAULT NULL,
  `NYFX_PRO_VALUE` text DEFAULT NULL,
  `NYFX_PRO_NORMAL` text DEFAULT NULL,
  `NYFX_PRO_NOTE` text DEFAULT NULL,
  `NYFX_SG_VALUE` text DEFAULT NULL,
  `NYFX_SG_NORMAL` text DEFAULT NULL,
  `NYFX_SG_NOTE` text DEFAULT NULL,
  `NYFX_UBG_VALUE` text DEFAULT NULL,
  `NYFX_UBG_NORMAL` text DEFAULT NULL,
  `NYFX_UBG_NOTE` text DEFAULT NULL,
  `NYFX_VC_VALUE` text DEFAULT NULL,
  `NYFX_VC_NORMAL` text DEFAULT NULL,
  `NYFX_VC_NOTE` text DEFAULT NULL,
  `ZYBS_VALUE` text DEFAULT NULL,
  `ZYBS_NORMAL` text DEFAULT NULL,
  `ZYBS_NOTE` text DEFAULT NULL,
  `ZYBS_1` text DEFAULT NULL,
  `ZYBS_2` text DEFAULT NULL,
  `ZYBS_3` text DEFAULT NULL,
  `ZYBS_4` text DEFAULT NULL,
  `ZYBS_5` text DEFAULT NULL,
  `ZYBS_6` text DEFAULT NULL,
  `ZYBS_7` text DEFAULT NULL,
  `ZYBS_8` text DEFAULT NULL,
  `ZYBS_9` text DEFAULT NULL,
  `YTB_HIP_VALUE` text DEFAULT NULL,
  `YTB_HIP_NORMAL` text DEFAULT NULL,
  `YTB_HIP_NOTE` text DEFAULT NULL,
  `YTB_WAIST_VALUE` text DEFAULT NULL,
  `YTB_WAIST_NORMAL` text DEFAULT NULL,
  `YTB_WAIST_NOTE` text DEFAULT NULL,
  `YTB_WHR_VALUE` text DEFAULT NULL,
  `YTB_WHR_NORMAL` text DEFAULT NULL,
  `YTB_WHR_NOTE` text DEFAULT NULL,
  `FGN_BZ_VALUE` text DEFAULT NULL,
  `FGN_BZ_NORMAL` text DEFAULT NULL,
  `FGN_BZ_NOTE` text DEFAULT NULL,
  `FGN_FEV1_VALUE` text DEFAULT NULL,
  `FGN_FEV1_NORMAL` text DEFAULT NULL,
  `FGN_FEV1_NOTE` text DEFAULT NULL,
  `FGN_FVC_VALUE` text DEFAULT NULL,
  `FGN_FVC_NORMAL` text DEFAULT NULL,
  `FGN_FVC_NOTE` text DEFAULT NULL,
  `FGN_PEF_VALUE` text DEFAULT NULL,
  `FGN_PEF_NORMAL` text DEFAULT NULL,
  `FGN_PEF_NOTE` text DEFAULT NULL,
  `SHILI_LEFT_EYE_VALUE` text DEFAULT NULL,
  `SHILI_LEFT_EYE_NORMAL` text DEFAULT NULL,
  `SHILI_LEFT_EYE_NOTE` text DEFAULT NULL,
  `SHILI_RIGHT_EYE_VALUE` text DEFAULT NULL,
  `SHILI_RIGHT_EYE_NORMAL` text DEFAULT NULL,
  `SHILI_RIGHT_EYE_NOTE` text DEFAULT NULL,
  `SEMANG_VALUE` text DEFAULT NULL,
  `SEMANG_NORMAL` text DEFAULT NULL,
  `SEMANG_NOTE` text DEFAULT NULL,
  `XLCP_HMDJL_VALUE` text DEFAULT NULL,
  `XLCP_HMDJL_NORMAL` text DEFAULT NULL,
  `XLCP_HMDJL_NOTE` text DEFAULT NULL,
  `XLCP_LNYY_VALUE` text DEFAULT NULL,
  `XLCP_LNYY_NORMAL` text DEFAULT NULL,
  `XLCP_LNYY_NOTE` text DEFAULT NULL,
  `XLCP_QXJKD_VALUE` text DEFAULT NULL,
  `XLCP_QXJKD_NORMAL` text DEFAULT NULL,
  `XLCP_QXJKD_NOTE` text DEFAULT NULL,
  `XLCP_RGZA_VALUE` text DEFAULT NULL,
  `XLCP_RGZA_NORMAL` text DEFAULT NULL,
  `XLCP_RGZA_NOTE` text DEFAULT NULL,
  `XLCP_SHMYD_VALUE` text DEFAULT NULL,
  `XLCP_SHMYD_NORMAL` text DEFAULT NULL,
  `XLCP_SHMYD_NOTE` text DEFAULT NULL,
  `XLCP_ZCJKPD_VALUE` text DEFAULT NULL,
  `XLCP_ZCJKPD_NORMAL` text DEFAULT NULL,
  `XLCP_ZCJKPD_NOTE` text DEFAULT NULL,
  `XLCP_EQ_VALUE` text DEFAULT NULL,
  `XLCP_EQ_NORMAL` text DEFAULT NULL,
  `XLCP_EQ_NOTE` text DEFAULT NULL,
  `XLCP_HFXX_VALUE` text DEFAULT NULL,
  `XLCP_HFXX_NORMAL` text DEFAULT NULL,
  `XLCP_HFXX_NOTE` text DEFAULT NULL,
  `XLCP_PSTR_VALUE` text DEFAULT NULL,
  `XLCP_PSTR_NORMAL` text DEFAULT NULL,
  `XLCP_PSTR_NOTE` text DEFAULT NULL,
  `XLCP_SMZKPG_VALUE` text DEFAULT NULL,
  `XLCP_SMZKPG_NORMAL` text DEFAULT NULL,
  `XLCP_SMZKPG_NOTE` text DEFAULT NULL,
  `XLCP_UCLA_VALUE` text DEFAULT NULL,
  `XLCP_UCLA_NORMAL` text DEFAULT NULL,
  `XLCP_UCLA_NOTE` text DEFAULT NULL,
  `XLCP_ZPYY_VALUE` text DEFAULT NULL,
  `XLCP_ZPYY_NORMAL` text DEFAULT NULL,
  `XLCP_ZPYY_NOTE` text DEFAULT NULL,
  `ACTIVE` varchar(1) DEFAULT '1',
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANSAKSI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




DROP TABLE IF EXISTS dt01_satusehat_bundle;

CREATE TABLE `dt01_satusehat_bundle` (
  `ORG_ID` varchar(36) DEFAULT NULL,
  `TRANSAKSI_ID` varchar(36) NOT NULL,
  `TRANS_ID` varchar(36) NOT NULL,
  `LOCATION` varchar(500) DEFAULT NULL,
  `RESOURCE_TYPE` varchar(100) DEFAULT NULL,
  `RESOURCE_ID` varchar(100) DEFAULT NULL,
  `ETAG` varchar(100) DEFAULT NULL,
  `STATUS` varchar(500) DEFAULT NULL,
  `LAST_MODIFIED` varchar(500) DEFAULT NULL,
  `JENIS` varchar(1) DEFAULT NULL,
  `NOTE` varchar(500) DEFAULT NULL,
  `ENVIRONMENT` varchar(500) DEFAULT NULL,
  `AKTIF` varchar(1) DEFAULT '1',
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TRANSAKSI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




